Issue #169 resolution proposal
PilotsTradeNetwork/MissionAlertBot pull request #178
Opened 2021-06-13 11:20 UTC by elliott-huge

Channel IDs for wine load alerts still needed for resolution to be final (I don't have access to these)
Use of a bool to implement slightly mission-posting different behavior in the event of a wine-load, checked by identifying the commodity
Message CMDR Bear_Grylls on Discord for queries/concerns

2021-06-13 11:35 UTC, gcruicks requested changes
Looks good, just needs the channel Id

2021-06-13 11:35 UTC, gcruicks commented on constants.py
> +TEST_WINE_ALERTS_ID = 0000 #TODO: get ID for #booze-cruise-loading-operations on test server
Use the test trade alerts is for this one

2021-06-13 11:35 UTC, gcruicks commented on constants.py
>  PROD_TRADE_ALERTS_ID = 801798469189763073  # trade alerts channel ID for PTN main server
Enable developer mode in discord, right click the channel and copy the ID, that is the value for here

2021-06-13 11:36 UTC, elliott-huge commented on constants.py
> +TEST_WINE_ALERTS_ID = 0000 #TODO: get ID for #booze-cruise-loading-operations on test server
Thanks! Where (which server) exactly does testing occur?

2021-06-14 18:17 UTC, gcruicks approved these changes

2021-06-14 18:19 UTC, merged