Replace Crew roles with single Hauler role
PilotsTradeNetwork/MissionAlertBot pull request #196
Opened 2021-08-12 18:19 UTC by cimspin

Closes #195

2021-08-13 21:35 UTC, gcruicks requested changes
Check the code path for adding a carrier still works, if yes then will approve this

2021-08-13 21:35 UTC, gcruicks commented on MissionAlertBot.py
> +                           (short_name.lower(), long_name.upper(), carrier_id.upper(), channel, channel_id, owner_id))
This is going to fail I think because the carrier DB expects the extra parameter to be present. We might need to write something up to remove that column from the data stream on start up if it exists, or consider to just dump a NULL value in as a temp stop gap until we get to that stage

2021-08-13 22:30 UTC, cimspin commented on MissionAlertBot.py
> +                           (short_name.lower(), long_name.upper(), carrier_id.upper(), channel, channel_id, owner_id))
It works so long as I remove the ROLEID column from the live database when updating. I was too brainfoggy to work out the issues involved in leaving the column in place but unused

2021-08-13 22:31 UTC, cimspin commented on MissionAlertBot.py
> +                           (short_name.lower(), long_name.upper(), carrier_id.upper(), channel, channel_id, owner_id))
If there's a way to remove the ROLEID column from the database programmatically on the first run of the script I guess that would be neat

2021-08-14 06:59 UTC, gcruicks commented on MissionAlertBot.py
> +                           (short_name.lower(), long_name.upper(), carrier_id.upper(), channel, channel_id, owner_id))
So I took a look, it is not as clean as I was hoping for it to be. You can pragmatically add columns, but to remove you need to do:

1. Make new table
2. Copy relevant data from old table to new
3. Drop old table
4. Rename new table to old table.

While it is possible to program it up, it just won't be as simple/straight forward as I had hoped for.

2021-08-14 06:59 UTC, gcruicks commented on MissionAlertBot.py
> +                           (short_name.lower(), long_name.upper(), carrier_id.upper(), channel, channel_id, owner_id))
I will approve this change on the basis you update the table yourself :)

2021-08-14 07:36 UTC, cimspin commented on MissionAlertBot.py
> +                           (short_name.lower(), long_name.upper(), carrier_id.upper(), channel, channel_id, owner_id))
Ok!

2021-08-15 16:57 UTC, merged