Notify CCO on m.done, reorganise m.done / m.complete to use new shared mission completion functions
PilotsTradeNetwork/MissionAlertBot pull request #249
Opened 2021-08-22 21:37 UTC by cimspin

Fixes #248 #241

2021-08-22 21:41 UTC, gcruicks commented on MissionAlertBot.py
> +            return await spamchannel.send(f"<@211891698551226368> WARNING: No channel lock available on {delchannel} after 120 seconds. Deletion aborted.")
hard coded user id here

2021-08-22 21:42 UTC, gcruicks commented on MissionAlertBot.py
> +                if desc_msg: reason = f"  Reason given:\n{desc_msg}"
put this on a new line please :)

2021-08-22 21:44 UTC, gcruicks commented on MissionAlertBot.py
> +                if desc_msg: reason = f"  Reason given:\n{desc_msg}"
Also needs defined (reason) for the negative case

2021-08-22 22:04 UTC, cimspin commented on MissionAlertBot.py
> +            return await spamchannel.send(f"<@211891698551226368> WARNING: No channel lock available on {delchannel} after 120 seconds. Deletion aborted.")
That's me!

2021-08-23 05:42 UTC, gcruicks requested changes
minor comments only

2021-08-23 05:42 UTC, gcruicks commented on MissionAlertBot.py
> +        mission_db.execute(f"DELETE FROM missions WHERE carrier = '{mission_data.carrier_name}' ;")
do you need the semi-colon here?

2021-08-23 05:42 UTC, gcruicks commented on MissionAlertBot.py
> +                reason = None if desc_msg == "" else desc_msg
`reason = desc_msg if desc_msg else None`, the positive case first makes it a bit more readable.

Also `if desc_msg == ''` can be caught with `if not desc_msg`

2021-08-23 09:50 UTC, cimspin commented on MissionAlertBot.py
> +        mission_db.execute(f"DELETE FROM missions WHERE carrier = '{mission_data.carrier_name}' ;")
Apparently not

2021-08-23 09:50 UTC, cimspin commented on MissionAlertBot.py
> +                reason = None if desc_msg == "" else desc_msg
Changes made

2021-08-23 22:11 UTC, merged