Edmc pin work
PilotsTradeNetwork/MissionAlertBot pull request #388
Opened 2022-10-29 17:46 UTC by skiedude

1. react EDMC OFF in emojis to the trade alert when edmc_off is True #384  
2. fix edmc typos #386 
3. clean up the bot pinned messages on m.done|m.complete  #383 
4. erase the system notification message that a message was pinned in all public guild channels #387

2022-10-29 21:00 UTC, cimspin requested changes
Also can we add to the Discord trade alert text (defined from line 850, `txt_create_discord`) the prefix `**EDMC-OFF MISSION: **` for EDMC-off missions? Just to thoroughly distinguish them from normal missions. Something like:

```def txt_create_discord(carrier_data, mission_type, commodity, station, system, profit, pads, demand, eta_text, mission_temp_channel_id, edmc_off):
    discord_channel = f"<#{mission_temp_channel_id}>" if mission_temp_channel_id else f"#{carrier_data.discord_channel}"
    discord_text ={" **EDMC-OFF MISSION: **" if edmc_off else ""} \
                   f"{discord_channel} {'load' if mission_type == 'load' else 'unload'}ing " \
                   f"{commodity.name} " \
                   f"{'from' if mission_type == 'load' else 'to'} **{station.upper()}** station in system " \
                   f"**{system.upper()}** : {profit}k per unit profit : "\
                   f"{demand} {'demand' if mission_type == 'load' else 'supply'} : {pads.upper()}-pads" \
                   f".{eta_text}"
    return discord_text```
    
You'd have to pass `edmc_off` to the `txt_create_discord function` from whereever `discord_text` is defined as well of course. But, eh, feel free to do it however you want, just slowly dusting off the coding section of my brain

2022-10-29 21:01 UTC, cimspin commented
Also, amazing work as usual

2022-10-29 22:41 UTC, skiedude commented
New trade alert message look:
![edmc_off](https://user-images.githubusercontent.com/6210395/198855060-ea47d9ca-cbc4-4d30-9b21-e6f9b5d970bd.png)

System notifications for pinned messages for normal users
![pin](https://user-images.githubusercontent.com/6210395/198855062-fd298674-53cf-439d-b4b9-35371bd4d783.png)

New prompt with the `e` option
![prompt](https://user-images.githubusercontent.com/6210395/198855063-a0ec8300-b7bc-4bbe-8546-5c4093917a8b.png)

2022-10-30 08:51 UTC, cimspin requested changes
Small nitpick on lines 1238-9 for stylistic reasons, otherwise good to go 👍

2022-10-30 08:51 UTC, cimspin commented on MissionAlertBot.py
> +                            description="(**d**)iscord, (**e**)dmc OFF, (**r**)eddit, (**t**)ext for copy/pasting or (**x**) to cancel\n"
`description="(**d**)iscord, (**r**)eddit, (**t**)ext for copy/pasting or (**x**) to cancel\n"`

2022-10-30 08:51 UTC, cimspin commented on MissionAlertBot.py
>                              "Use (**n**) to also notify PTN Haulers.",
`"Use (**n**) to notify PTN Haulers, and (**e**) to flag your mission as EDMC-OFF.",`

2022-10-30 15:18 UTC, skiedude commented
![edmc](https://user-images.githubusercontent.com/6210395/198886529-6f6b1a6a-ea65-4e82-bd22-6b0f76a920fc.png)

2022-10-30 20:19 UTC, cimspin approved these changes
Awesome stuff

2022-10-30 20:39 UTC, merged